name:                json-diff-adventar-bot
version:             0.1.0.0
homepage:            https://github.com/matsubara0507/json-diff-adventar-bot#readme
license:             MIT
author:              MATSUBARA Nobutada
copyright:           2017 MATSUBARA Nobutada
category:            Web
extra-source-files:
- README.md

dependencies:
  - aeson
  - aeson-pretty
  - base >= 4.7 && < 5
  - bytestring
  - mtl
  - slack-api
  - text
  - unordered-containers

executables:
  json-diff-bot:
    source-dirs:      src
    main:             Main.hs
